[package]
name = "nexus-reconfigurator-planning"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
internal-dns.workspace = true
ipnet.workspace = true
ipnetwork.workspace = true
nexus-config.workspace = true
nexus-inventory.workspace = true
nexus-types.workspace = true
omicron-common.workspace = true
slog.workspace = true
thiserror.workspace = true
uuid.workspace = true

# XXX-dap this needs to move back to dev-dependencies.  I moved it so I can
# expose the test module to another crate.
sled-agent-client.workspace = true

omicron-workspace-hack.workspace = true

[dev-dependencies]
omicron-test-utils.workspace = true
#sled-agent-client.workspace = true
