[package]
name = "wicket-dbg"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
anyhow.workspace = true
ciborium.workspace = true
clap.workspace = true
crossterm = { version = "0.26.1", features = ["event-stream"] }
serde.workspace = true
slog.workspace = true
tui = "0.19.0"
wicket.workspace = true

# used only by wicket-dbg binary
reedline = "0.17.0"

[[bin]]
name = "wicket-dbg"

[[bin]]
name = "wicket-dbg-server"
