[package]
name = "omicron-ipcc-rot"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[lints]
workspace = true

[build-dependencies]
omicron-rpaths.workspace = true

[dependencies]
ipcc.workspace = true
x509-cert.workspace = true
dice-verifier.workspace = true
pem-rfc7468 = { version = "0.7.0", default-features = false }
der = { version = "0.7.9" }
attest-data.workspace = true
hubpack = "0.1"

[dev-dependencies]

# Disable doc builds by default for our binaries to work around issue
# rust-lang/cargo#8373.  These docs would not be very useful anyway.
[[bin]]
name = "ipcc-rot"
doc = false
