p4_program = "/stuff/libsidecar_lite.so"
ports = [
    { sidecar = "rear0", scrimlet = "softnpu0_0", mtu = 1600 },
    { sidecar = "qsfp0", scrimlet = "softnpu0_1", mtu = 1500 },
    { sidecar = "sc0_2", scrimlet = "sr0_2", mtu = 1600 },
]
