[package]
name = "nexus-deployment"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
futures.workspace = true
nexus-types.workspace = true
omicron-common.workspace = true
slog.workspace = true
uuid.workspace = true

omicron-workspace-hack.workspace = true
