[package]
name = "wicket"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.25.0"
tui = "0.19.0"
#tokio = { version = "1.21.1", features = ["full"] }
anyhow = "1.0.65"

[[bin]]
name = "wicket"
doc = false
