[package]
name = "nexus-authn"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
async-trait = "0.1.56"
anyhow = "1.0"
base64 = "0.13.0"
chrono = { version = "0.4", features = ["serde"] }
cookie = "0.16"
headers = "0.3.7"
http = "0.2.7"
hyper = "0.14"
lazy_static = "1.4.0"
newtype_derive = "0.1.6"
# must match samael's crate!
openssl = "0.10"
openssl-sys = "0.9"
openssl-probe = "0.1.2"
samael = { git = "https://github.com/njaremko/samael", features = ["xmlsec"], branch = "master" }
serde = { version = "1.0", features = ["derive"] }
serde_urlencoded = "0.7.1"
slog = { version = "2.7", features = ["max_level_trace", "release_max_level_debug"] }
thiserror = "1.0"
uuid = { version = "1.1.0", features = ["serde", "v4"] }

dropshot = { git = "https://github.com/oxidecomputer/dropshot", branch = "main", features = ["usdt-probes"] }

omicron-common = { path = "../../../common" }

[dev-dependencies]
tokio = { version = "1.20", features = ["full"] }
